### ISSUE TITLE
TODO things that need to be done

### ISSUE THREAD

**Issue by kazdevl** [KazuwoKiwame12/notion-meeting-app#3]
- [x] write test code for config
- [x] corresponding to todo isue
- [x] select AWS or Heroku for deploy app
- [x] select MySQL or PostgreSQL for DB
- [x] write Dockerfile for above
- [x] implement db-operation
- [x] write test code for above
- [x] implement slack app and functon for slack
  - [x] slash_commands: /explain
  - [x] shortcut: modal for set and update notion infos
  - [x] slash_commands: /start
  - [x] slash_commands: /stop
  - [x] slash_commands: /all (for admin)
  - [x] slash_commands: /all-stop (for admin)
  - [x] notify
- [x] implement middleware for security and validation
- [x] write test code for above
- [ ] deploy application on docker to heroku 
- [ ] set CI/CD
- [ ] format the code
- [ ] consider architecture to improve maintainability
